### ISSUE TITLE
Request for Guidance

### ISSUE THREAD

**Issue by RTfxf** [GrandpaGameHacker/DS2Cam#1]
Excuse me，may I ask you a question? I don't know how to switch on this camera. Will it like the "DarkSoul DebugMenu"with the gamepad to activate the camera?

**Comment by GrandpaGameHacker** [comment]
Hit the insert button should do it
A console window should pop up with instructions when the DLL is injected

**Comment by RTfxf** [comment]
I put the "cameratools.dll" into the game root directory , should i hit "insert" in game to launch it?
I'm dreadfully sorry that I'm not familiar with using this , could you explain it in more detail? Thank you so much.

**Comment by GrandpaGameHacker** [comment]
Oh right
Extra thing. Make sure you are in offline play as it could cause ban if online

You need to inject the DLL into the game while it is running
try using either Cheat Engine or Process Hacker

**Comment by RTfxf** [comment]
You are quite right，absolutely keep offline。Thanks for your reply，I downloaded "Process Hacker" then I used it to see your menu , but I'm sorry I ran into another problem。
 In the menu, i saw that it displayed "waiting for camera structure intercept"。I waited for a while, and I didn't know what to do next。
 In the meantime，when I pressed "insert" in the game, there is still no change。Maybe I did something wrong in some step, so I still want to ask for your help。 
![屏幕截图 2022-11-18 110518](https://user-images.githubusercontent.com/118180932/202619237-d89fa9cc-b188-4d09-83cb-c043271475a6.jpg)
![屏幕截图 2022-11-18 110753](https://user-images.githubusercontent.com/118180932/202619299-f5900f86-2542-44ea-badb-2d58b2b1c433.jpg)

**Comment by GrandpaGameHacker** [comment]
Ah yep what version of the game are you running? SoFTS

**Comment by RTfxf** [comment]
Ver.1.03    Calibrations2.02

**Comment by GrandpaGameHacker** [comment]
My old project might be broken then if there was an update. I'll look at it this weekend hopefully

**Comment by RTfxf** [comment]
OK,thank you very much for your kind and serious attitude.

**Comment by GrandpaGameHacker** [comment]
@RTfxf  New fixed version for 1.03 calibrations 2.02
https://github.com/GrandpaGameHacker/DS2Cam/releases/tag/1.0.1/

**Comment by RTfxf** [comment]
I think this is the best camera script of DS2 . I have downloaded many CE scripts, but none of them have the function of free camera. anyhow, You made my wish come true. Thank you ,truely.
I don't know whether you will allow me to use your script in the video, because I want to make a Film editing of DS2.

**Comment by GrandpaGameHacker** [comment]
You have permission from me to use this tool for the purpose of recording. Thankyou for your kind words, its is mostly based off of Frans Bouma's earlier work and his Camera template. you should check them out. I just adjusted it to work for DS2 :)

https://github.com/FransBouma
https://github.com/FransBouma/InjectableGenericCameraSystem

**Comment by RTfxf** [comment]
Thank you for your permission. Compared with Eldenring, I cherish the memory of the majula.
There's no doubt about your's script is excellent , i'm looking foward to your more outstanding works in the future.
![Dark Souls II Screenshot 2022 11 22 - 22 24 49 88](https://user-images.githubusercontent.com/118180932/203624462-91917b38-e4d2-4290-aa6a-3f09e65e38b1.png)
